### ISSUE TITLE
Add info for necessary libs

### ISSUE THREAD

**Issue by vdm97** [nilgradisnik/markdown-rs#3]
Hi, great work so far. I wanted to dive in in your code, but faced some problems. Solving them was not very hard, but you should add the necessary libs for compiling in the README.md. That way a newcomers will have it easier :)

PS: I had to execute following commands on Ubuntu 18.04:

``
sudo apt install libwebkit2gtk-4.0-dev
``
``
sudo apt install ibgtksourceview-3.0-dev 
``

Also you should add that you cannot compile if you run Ubuntu 16.04 or lower because of dependency mess.. (there is no newer version of gdk available)

``
error: failed to run custom build command for gdk-sys v0.6.0
process didn't exit successfully: /markdown-rs/target/debug/build/gdk-sys-e2a4e4c35fe8cc31/build-script-build (exit code: 1)
``
``
--- stderr
"pkg-config" "--libs" "--cflags" "gdk-3.0 >= 3.22" did not exit successfully: exit code: 1
--- stderr
``
``
Requested gdk-3.0 >= 3.22 but version of GDK is 3.18.9
``
``
warning: build failed, waiting for other jobs to finish...
error: build failed
``

**Comment by nilgradisnik** [comment]
That's a good idea, I definitely need to expand the section on how to compile this and all the required dependencies. I honestly didn't even try compiling this on any other machine than my own Fedora 27 installation at this point.

Thanks for the feedback and info on which package need to be installed on Ubuntu. There's a brief section on requirements on  [gtk-rs](http://gtk-rs.org/docs-src/requirements.html) website. But this project is also using [sourceview](https://github.com/gtk-rs/sourceview) and [webkit2gtk](https://github.com/gtk-rs/webkit2gtk-rs) that's why you need those packages installed as well.
